### PR TITLE
Allow additional activity types

### PR DESCRIPTION
**Pull request by BenMQ**

### CODE REVIEW

**Comment by xinan** [comment]
Wow!

**Comment by BenMQ** [comment]
Not needed

**Comment by yangshun** [comment]
o.o are there new types of lessons these days?

**Comment by BenMQ** [comment]
I think there's always a long list, but those that are selected with > 0 hours by the instructor appears in our view.

**Comment by BenMQ** [comment]
See: https://github.com/nusmodifications/nus-scripts/commit/a0adaec953d233dc4fde7f05c53726da44839584

**Pull request closed without merging**
