### PR TITLE
Disclaimer Message: Fixed Typo

### PR DESCRIPTION
**Pull request by mauris**

### CODE REVIEW

**Comment by mauris** [comment]
@yangshun my bad, typo in message

**Comment by yangshun** [comment]
My bad, never read properly. Can you rebase and resolve conflicts first?

**Comment by yangshun** [comment]
@mauris Would like to resolve the conflicts first?

**Comment by mauris** [comment]
my bad, resolved

**Comment by yangshun** [comment]
Thanks!

**Pull request merged**
